language: c
compiler:
- gcc-4.8
- gcc-4.9
- gcc-5
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - gcc-4.8
    - gcc-4.9
    - gcc-5
    - cmake
script:
- mkdir build && cd build
- cmake -DDSLINK_TEST=ON ..
- cmake ..
- make
- make test

