language: c
sudo: false
compiler:
- clang
- gcc-4.8
- gcc-4.9
- gcc-5
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - gcc-4.9
    - gcc-5
script:
- mkdir build && cd build
- cmake -DDSLINK_BUILD_BROKER=true --DSLINK_BUILD_EXAMPLES=true ..
- make
- make test
