language: c
compiler:
- clang
- gcc-4.8
- gcc-4.9
- gcc-5
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - gcc-4.8
    - gcc-4.9
    - gcc-5
    - cmake
script:
- mkdir build && cd build
# - cmake -DDSLINK_BUILD_BROKER=true -DDSLINK_BUILD_EXAMPLES=true ..
- cmake ..
- make
#- make test

