language: c

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install jansson; fi

matrix:
  include:
  - os: linux
    compiler: clang
  - os: linux
    compiler: gcc-4.8
  - os: linux
    compiler: gcc-4.9
  - os: linux
    compiler: gcc-5
  - os: osx
    compiler: clang
  - os: osx
    compiler: gcc
    env: CMAKE_FLAGS=-DCMAKE_C_COMPILER=gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - gcc-4.8
    - gcc-4.9
    - gcc-5
    - cmake
    - libjansson-dev
    - libjansson4
script:
- mkdir build && cd build
- cmake -DDSLINK_TEST=ON ${CMAKE_FLAGS} ..
- make
- make test
